### ISSUE TITLE
Damage number transparency

### ISSUE THREAD

**Issue by 240hz** [240hz/ApexConfigs#2]
Damage number transparency, size, display time.
PLEASE GIVE DEVs

**Comment by kALLEBALIK** [comment]
Have you experimented with these values?

[ConVar."damage_indicator_style_pilot"]
	address = 0x2350a00
	flags = 0x1000000
	default_value = "2"
[ConVar."damage_indicator_style_titan"]
	address = 0x234e190
	flags = 0x1000000
	default_value = "1"
[ConVar."hud_setting_damageIndicatorStyle"]
	address = 0x2319ce0
	flags = 0x1000000
	default_value = "2"
[ConVar."hud_setting_damageTextStyle"]
	address = 0x2315030
	flags = 0x1000000
	default_value = "1"

Edit:
damage_indicator_style_pilot "3" // (0) 2d, (1) = 2d/3d both,  (3) 3d
damage_indicator_style_titan "1" // Probably nothing
hud_setting_damageIndicatorStyle "2" // crosshair damage feedback (0) off, (1) X, (2) X w/shield icon
hud_setting_damageTextStyle "1" // damage numbers,  (0) off, (1) stacking, (2) floating, (3) both

I'll keep looking.

**Comment by r1ft4469** [comment]
This is all I have found doesn't seem to work.
hud_setting_pingAlpha "0.500000"
