### ISSUE TITLE
no response after starting the game

### ISSUE THREAD

**Issue by prajna0** [240hz/ApexConfigs#5]
i  follow the instructions, but it doesn't work

**Comment by 240hz** [comment]
I need to fix README.md this is there but its easy to miss.

_**Try this.**_ `add exec "autoexec.cfg" at the end of profile.cfg. you will need to make profile.cfg read only or else it will over wright after execution.`

**Comment by 240hz** [comment]
for example you can look at this [profile.cfg](https://raw.githubusercontent.com/240hz/ApexConfigs/master/profile.cfg)

also you will need to remove ALL start up options

**Comment by prajna0** [comment]
thank you, i did it, it changed my button settings, i only need to improve fps, what files do i need to add?
i only added these files
autoexec.cfg console.cfg console2.cfg
videoconfig.txt profile.cfg
startup options: +exec autoexec profile.cfg

also, i am very dark in the room, which is the problem with which code?

cl_fovScale "1.55" //1.55 is 110 fov
i want to change to fov of 104, what number should i fill?

**Comment by Arnaud-Github** [comment]
cl_fovScale "1.55" //1.55 is 110 fov
i want to change to fov of 104, what number should i fill?

**Comment by Arnaud-Github** [comment]
i only added these files
autoexec.cfg console.cfg console2.cfg
videoconfig profile.cfg
Startup item: +exec autoexec profile.cfg

**Comment by 240hz** [comment]
for the correct FOV value you want to use set it in the game and it will be written in profile.cfg. you can disable the command from activating by putting 2 slashes // in front of it also.

For fps you want to use videoconfig.txt just make sure you set your resolution inside then make it read only. The autoexec.cfg also has the videoconfig.txt commands in it so you could use either one. 

```
mat_autoexposure_min 1.50
mat_autoexposure_max 1.50
mat_autoexposure_override_min_max 1.50
```
these commands can brightening up the game. try 1.25 if 1.5 is too bright or 1.15. I think 1 is default

**Comment by prajna0** [comment]
thank you very much, i only used videoconfig.txt and I have a lot of improvements to FPS. mendokusaii also use this videoconfig?

**Comment by 240hz** [comment]
> 
> 
> thank you very much, i only used videoconfig.txt and I have a lot of improvements to FPS. mendokusaii also use this videoconfig?

I believe mendo was using a similar video config at 1 point. happy the config helped!
