### ISSUE TITLE
console.cfg is missing

### ISSUE THREAD

**Issue by T3h-vICE** [240hz/ApexConfigs#8]
Hi, i can't see the console.cfg's. Are they missing in the repository?

**Comment by 240hz** [comment]
I use console.cfg's for testing and tuning sets of commands also different bind profiles. 


example.  different Exposure values so to can toggle between, 

```
mat_autoexposure_override_min_max "1"
mat_autoexposure_max "1.9"                    // default 2, set to 1 and min to 0.8 to slightly lower the exposure of the world
mat_autoexposure_min "1.9"                    //default 0.5
mat_autoexposure_speed "2"                      // Speed between the exposure changes
mat_autoexposure_uncap "0"
mat_autoexposure_max_multiplier "1.7"
mat_autoexposure_min_multiplier "1.7"
mat_colorcorrection "1"
mat_colorcorrection_editor "1"
```


Here is a sus af console cfg [sus.cfg](https://github.com/240hz/ApexConfigs/raw/master/SUS.CFG) 

https://github.com/240hz/ApexConfigs/commit/c9d43a6f7a87dcf7ad8e5fb66653c24b142859c3#diff-62b2abacb978f774779ad875578fe66e
